export const BACKUP = {
  league: {
    currentWeekStandings: [
      {
        id: "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1",
        winningPercentage: 0,
        rank: 1,
        record: { wins: 0, ties: 0, losses: 0 },
      },
      {
        id: "9r79U8lERjgX50MYFPhAgHhkVn33",
        record: { wins: 0, ties: 0, losses: 0 },
        winningPercentage: 0,
        rank: 1,
      },
      {
        id: "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
        rank: 1,
        winningPercentage: 0,
        record: { wins: 0, ties: 0, losses: 0 },
      },
      {
        winningPercentage: 0,
        rank: 1,
        record: { wins: 0, ties: 0, losses: 0 },
        id: "PH20XRhudLX1SIN7SVH5foLXawY2",
      },
      {
        id: "uZQfFwv22JeAoAE5t12CsnjKe603",
        rank: 1,
        winningPercentage: 0,
        record: { losses: 0, wins: 0, ties: 0 },
      },
      {
        record: { ties: 0, wins: 0, losses: 0 },
        winningPercentage: 0,
        rank: 1,
        id: "DHU1ls2NhpUda1DqSyYE5bKQUK63",
      },
      {
        id: "evDAfugUS7X86pGL4yOLGX3Q8P02",
        rank: 1,
        winningPercentage: 0,
        record: { wins: 0, ties: 0, losses: 0 },
      },
    ],
    lastUpdatedAt: "2026-07-17T12:18:03.042Z",
    userIds: [
      "evDAfugUS7X86pGL4yOLGX3Q8P02",
      "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
      "PH20XRhudLX1SIN7SVH5foLXawY2",
      "uZQfFwv22JeAoAE5t12CsnjKe603",
      "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1",
      "DHU1ls2NhpUda1DqSyYE5bKQUK63",
      "9r79U8lERjgX50MYFPhAgHhkVn33",
    ],
    lastComputedWeek: "week-1-year-2026-type-2",
    key: "1757565255954",
    id: "league_1757565255954",
    name: "Sancheesy League",
    allTimeStandings: [
      {
        gamesBack: 0,
        record: { losses: 0, wins: 0, ties: 0 },
        rank: 1,
        winningPercentage: 0,
        id: "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1",
      },
      {
        id: "9r79U8lERjgX50MYFPhAgHhkVn33",
        rank: 1,
        winningPercentage: 0,
        gamesBack: 0,
        record: { losses: 0, ties: 0, wins: 0 },
      },
      {
        id: "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
        rank: 1,
        winningPercentage: 0,
        gamesBack: 0,
        record: { wins: 0, ties: 0, losses: 0 },
      },
      {
        record: { ties: 0, wins: 0, losses: 0 },
        gamesBack: 0,
        winningPercentage: 0,
        rank: 1,
        id: "PH20XRhudLX1SIN7SVH5foLXawY2",
      },
      {
        id: "uZQfFwv22JeAoAE5t12CsnjKe603",
        record: { losses: 0, wins: 0, ties: 0 },
        gamesBack: 0,
        winningPercentage: 0,
        rank: 1,
      },
      {
        id: "DHU1ls2NhpUda1DqSyYE5bKQUK63",
        record: { losses: 0, ties: 0, wins: 0 },
        gamesBack: 0,
        winningPercentage: 0,
        rank: 1,
      },
      {
        winningPercentage: 0,
        rank: 1,
        record: { ties: 0, wins: 0, losses: 0 },
        gamesBack: 0,
        id: "evDAfugUS7X86pGL4yOLGX3Q8P02",
      },
    ],
    computedWeekStandings: {
      "week-1-year-2026-type-2": [
        {
          id: "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1",
          record: { ties: 0, wins: 0, losses: 0 },
          winningPercentage: 0,
          rank: 1,
        },
        {
          rank: 1,
          winningPercentage: 0,
          record: { ties: 0, wins: 0, losses: 0 },
          id: "9r79U8lERjgX50MYFPhAgHhkVn33",
        },
        {
          id: "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
          rank: 1,
          winningPercentage: 0,
          record: { losses: 0, ties: 0, wins: 0 },
        },
        {
          winningPercentage: 0,
          rank: 1,
          record: { ties: 0, wins: 0, losses: 0 },
          id: "PH20XRhudLX1SIN7SVH5foLXawY2",
        },
        {
          rank: 1,
          winningPercentage: 0,
          record: { ties: 0, wins: 0, losses: 0 },
          id: "uZQfFwv22JeAoAE5t12CsnjKe603",
        },
        {
          id: "DHU1ls2NhpUda1DqSyYE5bKQUK63",
          rank: 1,
          winningPercentage: 0,
          record: { ties: 0, wins: 0, losses: 0 },
        },
        {
          rank: 1,
          winningPercentage: 0,
          record: { losses: 0, wins: 0, ties: 0 },
          id: "evDAfugUS7X86pGL4yOLGX3Q8P02",
        },
      ],
    },
  },
  users: [
    {
      iconCharacter: "",
      email: "zieksanchez3@gmail.com",
      id: "evDAfugUS7X86pGL4yOLGX3Q8P02",
      username: "Bruhdot",
      leagueId: "league_1757565255954",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocKlTpxSZKngf6sfCMZmcSkGj9YyDxrnzrgH4t00DtB80pnD8g=s96-c",
      color: "#14b8a6",
    },
    {
      id: "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
      leagueId: "league_1757565255954",
      username: "ricksanchez3@yahoo.com",
      color: "rgba(179, 35, 164, 1)",
      photoURL: null,
      iconCharacter: "",
      email: "ricksanchez3@yahoo.com",
    },
    {
      email: "amanda3491@gmail.com",
      iconCharacter: "",
      color: "rgba(179, 35, 164, 1)",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocLxHA94t-hi28VTAlXV8jdK2OFIb1ChPSIMzGOoxU11vavF_Q=s96-c",
      id: "PH20XRhudLX1SIN7SVH5foLXawY2",
      leagueId: "league_1757565255954",
      username: "amanda3491@gmail.com",
    },
    {
      username: "Big Cheesie",
      leagueId: "league_1757565255954",
      id: "uZQfFwv22JeAoAE5t12CsnjKe603",
      color: "#fbbf24",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocLjDSu3OevSOuKeONNJ_TJTcvZpenpaM15NLd-0LmB_Pj94cQ=s96-c",
      iconCharacter: "",
      email: "mumychelsea@gmail.com",
    },
    {
      iconCharacter: "",
      email: "samanthasanchez887@gmail.com",
      username: "forg",
      leagueId: "league_1757565255954",
      id: "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1",
      color: "#84cc16",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocJfxeBJNP6tGqkLetSgX_VDV0VZ9gVBFVyoNng3-b-lwjxHpXjj=s96-c",
    },
    {
      iconCharacter: "",
      email: "ovaisqureshi77@gmail.com",
      username: "ovaisqureshi77@gmail.com",
      leagueId: "league_1757565255954",
      id: "DHU1ls2NhpUda1DqSyYE5bKQUK63",
      color: "rgba(179, 35, 164, 1)",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocInHVAPx9zFNbStG9Vj6rwWV5lRSKaenVw89zeK6bPRYiJE0jeT=s96-c",
    },
    {
      iconCharacter: "",
      email: "test@test.com",
      username: "test@test.com",
      id: "9r79U8lERjgX50MYFPhAgHhkVn33",
      leagueId: "league_1757565255954",
      photoURL: null,
      color: "rgba(179, 35, 164, 1)",
    },
  ],
  picks: [
    { picks: {}, username: "Bruhdot", id: "evDAfugUS7X86pGL4yOLGX3Q8P02" },
    {
      id: "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
      username: "ricksanchez3@yahoo.com",
      picks: {},
    },
    {
      username: "amanda3491@gmail.com",
      id: "PH20XRhudLX1SIN7SVH5foLXawY2",
      picks: {},
    },
    { id: "uZQfFwv22JeAoAE5t12CsnjKe603", username: "Big Cheesie", picks: {} },
    { picks: {}, username: "forg", id: "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1" },
    {
      username: "ovaisqureshi77@gmail.com",
      id: "DHU1ls2NhpUda1DqSyYE5bKQUK63",
      picks: {},
    },
    {
      id: "9r79U8lERjgX50MYFPhAgHhkVn33",
      username: "test@test.com",
      picks: {},
    },
  ],
};
