export const BACKUP = {
  league: {
    name: "Sancheesy League",
    lastUpdatedAt: "2026-07-15T23:31:13.608Z",
    lastComputedWeek: "week-1-year-2026-type-2",
    computedWeekStandings: {},
    id: "league_1757565255954",
    allTimeStandings: [
      {
        rank: 1,
        gamesBack: 0,
        winningPercentage: 0,
        record: { wins: 0, ties: 0, losses: 0 },
        id: "DHU1ls2NhpUda1DqSyYE5bKQUK63",
      },
      {
        winningPercentage: 0,
        gamesBack: 0,
        rank: 1,
        record: { losses: 0, wins: 0, ties: 0 },
        id: "evDAfugUS7X86pGL4yOLGX3Q8P02",
      },
      {
        gamesBack: 0,
        winningPercentage: 0,
        rank: 1,
        record: { losses: 0, ties: 0, wins: 0 },
        id: "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1",
      },
      {
        rank: 1,
        winningPercentage: 0,
        gamesBack: 0,
        record: { wins: 0, ties: 0, losses: 0 },
        id: "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
      },
      {
        record: { wins: 0, ties: 0, losses: 0 },
        id: "uZQfFwv22JeAoAE5t12CsnjKe603",
        winningPercentage: 0,
        gamesBack: 0,
        rank: 1,
      },
      {
        winningPercentage: 0,
        gamesBack: 0,
        rank: 1,
        record: { ties: 0, wins: 0, losses: 0 },
        id: "PH20XRhudLX1SIN7SVH5foLXawY2",
      },
    ],
    key: "1757565255954",
    userIds: [
      "evDAfugUS7X86pGL4yOLGX3Q8P02",
      "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
      "PH20XRhudLX1SIN7SVH5foLXawY2",
      "uZQfFwv22JeAoAE5t12CsnjKe603",
      "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1",
      "DHU1ls2NhpUda1DqSyYE5bKQUK63",
    ],
    currentWeekStandings: [
      {
        rank: 1,
        winningPercentage: 0,
        record: { ties: 0, wins: 0, losses: 0 },
        id: "DHU1ls2NhpUda1DqSyYE5bKQUK63",
      },
      {
        rank: 1,
        id: "evDAfugUS7X86pGL4yOLGX3Q8P02",
        winningPercentage: 0,
        record: { wins: 0, ties: 0, losses: 0 },
      },
      {
        record: { losses: 0, ties: 0, wins: 0 },
        id: "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1",
        winningPercentage: 0,
        rank: 1,
      },
      {
        winningPercentage: 0,
        record: { ties: 0, wins: 0, losses: 0 },
        id: "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
        rank: 1,
      },
      {
        rank: 1,
        winningPercentage: 0,
        id: "uZQfFwv22JeAoAE5t12CsnjKe603",
        record: { ties: 0, wins: 0, losses: 0 },
      },
      {
        rank: 1,
        record: { ties: 0, wins: 0, losses: 0 },
        id: "PH20XRhudLX1SIN7SVH5foLXawY2",
        winningPercentage: 0,
      },
    ],
  },
  users: [
    {
      color: "#14b8a6",
      id: "evDAfugUS7X86pGL4yOLGX3Q8P02",
      username: "Bruhdot",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocKlTpxSZKngf6sfCMZmcSkGj9YyDxrnzrgH4t00DtB80pnD8g=s96-c",
      leagueId: "league_1757565255954",
      email: "zieksanchez3@gmail.com",
      iconCharacter: "",
    },
    {
      iconCharacter: "",
      email: "ricksanchez3@yahoo.com",
      username: "ricksanchez3@yahoo.com",
      color: "rgba(179, 35, 164, 1)",
      id: "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
      leagueId: "league_1757565255954",
      photoURL: null,
    },
    {
      iconCharacter: "",
      email: "amanda3491@gmail.com",
      username: "amanda3491@gmail.com",
      color: "rgba(179, 35, 164, 1)",
      id: "PH20XRhudLX1SIN7SVH5foLXawY2",
      leagueId: "league_1757565255954",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocLxHA94t-hi28VTAlXV8jdK2OFIb1ChPSIMzGOoxU11vavF_Q=s96-c",
    },
    {
      username: "Big Cheesie",
      color: "#fbbf24",
      id: "uZQfFwv22JeAoAE5t12CsnjKe603",
      leagueId: "league_1757565255954",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocLjDSu3OevSOuKeONNJ_TJTcvZpenpaM15NLd-0LmB_Pj94cQ=s96-c",
      iconCharacter: "",
      email: "mumychelsea@gmail.com",
    },
    {
      username: "forg",
      color: "#84cc16",
      id: "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1",
      leagueId: "league_1757565255954",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocJfxeBJNP6tGqkLetSgX_VDV0VZ9gVBFVyoNng3-b-lwjxHpXjj=s96-c",
      iconCharacter: "",
      email: "samanthasanchez887@gmail.com",
    },
    {
      iconCharacter: "",
      email: "ovaisqureshi77@gmail.com",
      username: "ovaisqureshi77@gmail.com",
      id: "DHU1ls2NhpUda1DqSyYE5bKQUK63",
      color: "rgba(179, 35, 164, 1)",
      leagueId: "league_1757565255954",
      photoURL:
        "https://lh3.googleusercontent.com/a/ACg8ocInHVAPx9zFNbStG9Vj6rwWV5lRSKaenVw89zeK6bPRYiJE0jeT=s96-c",
    },
  ],
  picks: [
    { username: "Bruhdot", id: "evDAfugUS7X86pGL4yOLGX3Q8P02", picks: {} },
    {
      username: "ricksanchez3@yahoo.com",
      id: "YK5kmp0BMzVpLK2wT0eLzDr9XdB3",
      picks: {},
    },
    {
      username: "amanda3491@gmail.com",
      id: "PH20XRhudLX1SIN7SVH5foLXawY2",
      picks: {},
    },
    { username: "Big Cheesie", id: "uZQfFwv22JeAoAE5t12CsnjKe603", picks: {} },
    { picks: {}, username: "forg", id: "WHzLHaFF9wXMYaAYQCJ2ev5zOXq1" },
    {
      username: "ovaisqureshi77@gmail.com",
      id: "DHU1ls2NhpUda1DqSyYE5bKQUK63",
      picks: {},
    },
  ],
};
